[phases.setup]
nixPkgs = ["unzip", "bun"]
nixpkgsArchive = "b49f9222cd683837c28becdf09428b8990a551d1"

[phases.install]
cmds = ['bun install']

[phases.build]
cmds = ['turbo db:generate', 
        'turbo build --filter @chad-chat/brain']

[start]
cmd = 'bun --filter "./apps/brain" prod:release'