[phases.bun]
cmds=["curl -fsSL https://bun.sh/install | bash"]
paths = ["~/.bun/bin"]
dependsOn=["setup"]

[phases.install]
cmds = ['bun install']

[phases.build]
cmds = ['turbo db:generate', 
        'turbo build --filter @chad-chat/hub']