name: Code Quality

on:
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run check-types

      - name: Lint and Format check
        run: bun run fmt-lint

      - name: Cache Turborepo
        uses: actions/cache@v3
        with:
          path: |
            .turbo
            node_modules
            **/node_modules
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Build Docker image
        run: docker build -t netko:latest .
