name: Deploy Chad Chat

on:
  push:
    branches: [main]
    paths:
      - 'apps/hub/**'

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Type check
        run: bun run check-types
      - name: Lint and Format check
        run: bun run fmt-lint
      - name: Cache Turborepo
        uses: actions/cache@v3
        with:
          path: |
            .turbo
            node_modules
            **/node_modules
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

  docker-build:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: |
          docker build -t chad-chat .

  deploy:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Chad Chat
        run: |
          bash -c "${{ secrets.DEPLOY_HUB_CURL }}" 